version: "3.9"

services:
  ubuntu:
    container_name: ubuntu
    build:
        context: .
        dockerfile: ./Dockerfile
    ports:
      - "8000:5000"
    volumes:
      - ./:/shared:z
